# Generated by Django 2.0.10 on 2019-02-03 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('doc_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbox.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='PressureReading',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('mean_pressure', models.FloatField()),
                ('hand', models.CharField(max_length=10)),
                ('type_of_reading', models.IntegerField()),
            ],
        ),
    ]
