# Generated by Django 2.0.4 on 2019-02-18 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dbox', '0003_auto_20190204_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressurereading',
            name='time',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
