# Generated by Django 2.0.4 on 2019-02-18 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbox', '0004_pressurereading_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressurereading',
            name='pat_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dbox.Patient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pressurereading',
            name='type_of_reading',
            field=models.CharField(max_length=30),
        ),
    ]
