# Generated by Django 2.0.4 on 2019-02-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbox', '0005_auto_20190218_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressurereading',
            name='time',
            field=models.CharField(max_length=30),
        ),
    ]
